name: CI

on:
  - push
  - pull_request

jobs:
  ubuntu_test:
    name: (Ubuntu) Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets

  macos_test:
    name: (MacOS) Cargo Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: "an apple, a day"
        run: PATH="$PATH:${{ github.workspace }}/target/release" say $(pho o1)
