name: CI

on:
  - push
  - pull_request

jobs:
  ubuntu_test:
    name: (Ubuntu) Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: test

  macos_test:
    name: (MacOS) Cargo Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: test
